hashicorp/terraform-provider-consul

website/docs/r/service.html.markdown
The `consul_service` resource is not something most users should use, since service registration is normally done by a Consul Agent once a machine is running rather than via an external API call during provisioning.
The name of this resource makes it a bit of an attractive nuisance for those intending instead to register [External Services](https://www.consul.io/docs/guides/external.html). For that, the `consul_catalog_entry` resource is the right approach since it allows creation of a service entry that isn't associated with a "real" node.
=> website: attempt to dissuade use of consul_service

examples/kv/main.tf
This example reads a key using a `consul_keys` `resource,` which produces the warning:
```
* consul_keys.input: "key.0.name": [DEPRECATED] Using consul_keys resource to *read* is deprecated; please use consul_keys data source instead
```
Switching to the `consul_keys` `data` source fixes it (though not the other two erroneous
warnings caused by consul_keys being used to write)
=> Fix consul_keys deprecation warning.

website/docs/d/agent_self.html.markdown
This PR removes a double underscore in the title for the `consul_agent_self`  data source.
=> d/consul_agent_self: Fix double underscore in title (doc)

consul/resource_consul_service.go, consul/resource_consul_service_test.go, consul/test-fixtures/docker/docker-compose.yml
GH-23
I used aws_eip handling of not finding an EIP it thinks it should have based on state file.  https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_eip.go#L170-L172
Basically, ignore the missing service and the plan/apply will recreate.  Refresh will remove it from the tfstate as a side effect.  I believe this is all expected behavior for this scenario.
How I did real-world testing:
```hcl
resource "consul_service" "google" {
address = "www.google.com"
name    = "google"
port    = 80
tags    = ["tag0", "tag1"]
}
```
```bash
mkdir -p test-tf/plugins
make build
cp ../../../../bin/terraform-provider-consul test-tf/plugins/
cd test-tf
terraform init -plugin-dir plugins
terraform apply
curl http://localhost:8500/v1/agent/services
curl -X PUT …
```
=> GH-23: Handle missing service

consul/data_source_consul_catalog_service.go, consul/data_source_consul_catalog_service_test.go
GH-29
I was able to reproduce the issue reported in GH-29 simply by adding a test case.  The solution proposed to make these optional instead of computed made things work.
I created a separate test function because the basic doesn't necessarily work out of the box and I didn't want to expand the scope of this easy fix.
```bash
$ make testacc TESTARGS='-run=TestAccDataConsulCatalogService_filtered'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataConsulCatalogService_filtered -timeout 120m
?   	github.com/terraform-providers/terraform-provider-consul	[no test files]
=== RUN   TestAccDataConsulCatalogService_filtered
--- PASS: TestAccDataConsulCatalogService_filtered (0.11s)
PASS
ok …
```
=> GH-29: Make tag and datacenter optional to allow them to be used

consul/config.go, consul/resource_provider.go, consul/resource_provider_test.go, website/docs/index.html.markdown
#6 
This adds the insecure option.  I used `insecure` instead of `ssl_verify` because I saw the same option in OpenStack provider so thought it would be more acceptable.  https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L28
I haven't been able to do a real world test against an insecure endpoint.  I might be able to do that tomorrow.
```bash
$ make testacc TESTARGS='-run=TestResourceProvider'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestResourceProvider -timeout 120m
?   	github.com/terraform-providers/terraform-provider-consul	[no test files]
=== RUN   TestResourceProvider
--- PASS: TestResourceProvider (0.00s)
=== RUN   TestResourceProvider_impl
--- PASS: …
```
=> Add insecure option as requested in GH-6

website/docs/index.html.markdown
Should help differentiate between what the remote state backend is used
for and when it's used, versus the provider and when it should be used.
Fixes #22.
=> Docs: Add note about differences between provider and backend

consul/data_source_consul_agent_config.go, consul/data_source_consul_agent_config_test.go, consul/resource_provider.go, website/consul.erb, website/docs/d/agent_config.html.markdown
While attempting to get this providers acceptance tests passing on the latest version of Consul I noticed that the `consul_agent_self` data source largely did not work due to API changes in Consul.
This new datasource provides information similar to `consul_agent_self`, but is designed to only expose configuration that Consul will not change without versioning upstream.
In the 1.0 release of Consul, the [`/v1/agent/self`](https://www.consul.io/api/agent.html#read-configuration) endpoint was [modified](https://www.consul.io/docs/upgrade-specific.html#config-section-of-agent-self-endpoint-has-changed) to only expose specific config information, rather than internal Consul data structures that were subject to change without warning.
This internal structure is still available on that API, but …
=> New data source: consul_agent_config

.travis.yml
A PR is using the `t.Helper()` function, and the version of Go Travis is running with is so outdated, that doesn't exist. This updates Travis to the latest version of Go.
=> Update Travis to new version of Go

consul/resource_consul_node.go, consul/resource_consul_node_test.go, website/docs/r/node.html.markdown
Minor additions to the PR from @lawliet89 and @Zeldhyr renaming "node_meta" to "meta" in the TF resource. This aligns well with Terraform, and it shows up in both ways on the Consul API.
Closes #55 #38 #40
=> Add node-meta

website/docs/d/key_prefix.html.markdown
This fixes the documentation mistake to properly demonstrate the use of the subkeys hash.
=> Fix #66 with document update

website/docs/d/key_prefix.html.markdown
Example is missing the `subkeys` attribute.
=> Fix example code in consul_key_prefix doc

CHANGELOG.md, consul/resource_consul_intention.go, consul/resource_consul_intention_test.go, consul/resource_consul_node.go, consul/resource_consul_node_test.go, consul/resource_consul_service.go, consul/resource_consul_service_test.go
This changeset fixes an edge case of https://github.com/terraform-providers/terraform-provider-consul/pull/33 where if terraform state has consul catalog resource but consul catalog is actually empty the provider will raise an error rather than creating the node or service.
Acceptance Tests:
```
→ make testacc TEST=./consul TESTARGS="-run=TestAccConsulNode_basic"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./consul -v -run=TestAccConsulNode_basic -timeout 120m
=== RUN   TestAccConsulNode_basic
--- PASS: TestAccConsulNode_basic (0.06s)
PASS
ok      github.com/terraform-providers/terraform-provider-consul/consul 0.107s
→ make testacc TEST=./consul TESTARGS="-run=TestAccConsulService_basic"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go …
```
=> Create node and service if deleted outside of terraform

website/docs/d/agent_config.html.markdown
The listed HCL example does not work in terraform 11.11. The output structure is incorrect (needs value instead of a variable name) as is the reference format (missing the name section). The new example works as tested on v0.11.11 against consul 1.4.
=> Fix example HCL for consul_agent_config data resource

consul/resource_consul_key_prefix.go, website/docs/r/key_prefix.html.markdown
`consul_key_prefix` protect operators against unwanted key deletions by
requiring the choosen path to be empty.
While this is a nice default behavior, it can be intrusive to force it.
This change makes add import support to `consul_key_prefix` so the
operator can manually initialize Terraform state and override the default
behavior.
Close #77
=> Add import support to `consul_key_prefix`

consul/resource_consul_prepared_query.go, consul/resource_consul_prepared_query_test.go, website/docs/r/prepared_query.markdown
Quick add for querying for Consul Connect sidecars in prepared queries.  Probably needs a test but wanted to see if anything else might be needed as well.  Thanks!
=> Add Consul Connect support to prepared queries.

consul/resource_consul_acl_policy.go, consul/resource_consul_acl_policy_test.go, consul/resource_consul_acl_token.go, consul/resource_consul_acl_token_test.go, website/docs/r/acl_policy.html.markdown, website/docs/r/acl_token.html.markdown
Updating the policies associated with the anonymous token and the master token require them to be importable.
Fix https://github.com/terraform-providers/terraform-provider-consul/issues/100
=> Make consul acl {token,policy} importable

consul/resource_consul_acl_policy.go, consul/resource_consul_acl_policy_test.go, consul/resource_consul_acl_token.go, consul/resource_consul_acl_token_test.go, website/docs/r/acl_policy.html.markdown, website/docs/r/acl_token.html.markdown
I made a mistake during the review of #60, updating tokens currently crashes Terraform because of the wrong type assertion at https://github.com/terraform-providers/terraform-provider-consul/blob/master/consul/resource_consul_acl_token.go#L124.
=> Fix update of consul_acl_token

consul/resource_consul_node.go, consul/resource_consul_node_test.go, consul/resource_consul_service.go, consul/resource_consul_service_test.go, website/docs/r/service.html.markdown, website/docs/upgrading.html.markdown
`consul_node` were not updating their `address` and `meta` attributes during plans. This let another bug go unnoticed where `consul_service` could change `consul_node` attributes when `external` would be set to `true` (see https://github.com/terraform-providers/terraform-provider-consul/issues/101).
Multiple services could have conflicting configuration:
``` terraform
resource "consul_node" "compute" {
name    = "compute-example"
address = "www.hashicorptest.com"
}
resource "consul_service" "example1" {
name = "example"
node = "${consul_node.compute.name}"
port = 80
external = true
}
resource "consul_service" "example2" {
name = "example"
node = "${consul_node.compute.name}"
port = 80
external = true
}
// What should be the node's meta.external-probe and meta.external-node?
```
This patch …
=> Fix consul_node not detecting changes

website/docs/r/acl_policy.html.markdown, website/docs/r/acl_token.html.markdown
Let's hope it fixes the website highlighting.
https://www.terraform.io/docs/providers/consul/r/acl_token.html
=> Fix examples in acl_token and acl_policy documentation

CHANGELOG.md, consul/resource_consul_acl_token.go, consul/resource_consul_acl_token_test.go
It's more a question than a real PR.
Shouldn't the `local` attribute be set to `ForceNew`? It fails witha 500 or crashes doing `panic: interface conversion : interface {} is *schema.Set, not []interface {}` in `consul.resourceConsulACLTokenUpdate` (line 124) using the provider 2.3.0_x4 and a Consul 1.5.1 server.
```text
=== RUN   TestAccConsulACLToken_basic
--- FAIL: TestAccConsulACLToken_basic (0.06s)
testing.go:538: Step 1 error: Error applying: 1 error occurred:
* consul_acl_token.test: 1 error occurred:
* consul_acl_token.test: error updating ACL token "d56b4d5f-ed65-3ed4-2064-94935b5bf129": Unexpected response code: 500 (cannot toggle local mode of d56b4d5f-ed65-3ed4-2064-94935b5bf129)
```
Cheers,
=> Mark local attribute of consul_acl_token as ForceNew

website/docs/r/acl_policy.html.markdown
Adding the supported version to the description prevents users to raise issue if they are using an older version of Consul and Terraform which doesn't provide the feature.
=> added warning so users are aware of the prerequisite

consul/resource_consul_service.go, consul/resource_consul_service_test.go, go.sum
When we register 2 services with same name but different service_id the registrations fails with 500 code error:
2 error(s) occurred:
* consul_service.proxy_http: 1 error(s) occurred:
* consul_service.proxy_http: Failed to register service (dc: ''): Unexpected response code: 500 (rpc error making call: Unknown service 'proxy' for check 'proxy-http-check')
* consul_service.proxy_socks: 1 error(s) occurred:
* consul_service.proxy_socks: Failed to register service (dc: ''): Unexpected response code: 500 (rpc error making call: Unknown service 'proxy' for check 'proxy-socks-check')
This PR fix this issue and makes the correct check service association with service_id instead of service name.
BR
=> Use service_id instead of name when registering health-checks

consul/data_source_consul_service.go, consul/data_source_consul_service_test.go, website/docs/d/service.html.markdown
Implementing the changes described in Issue https://github.com/terraform-providers/terraform-provider-consul/issues/132, i.e. adding the ability to retrieve metadata using a service data source.
=> Add meta attribute in the consul_service datasource

consul/data_source_consul_service_health_test.go
Since https://github.com/hashicorp/consul/commit/4eb73973b6e53336fd505dc727ac84c1f7e78872
Consul store additional information in its service metadata field.
=> Update tests for Consul 1.5.2

consul/resource_consul_service.go, website/docs/r/service.html.markdown
This value changes when a service goes from "passing" to "critical" or
"warning" so it needs to be set as Computed or Terraform will
constantly create plans to set it back to the config value.
=> Mark consul_service.check.status as computed

CHANGELOG.md, consul/config.go, website/docs/index.html.markdown
This change allows the Consul provider to leverage the same Consul client environment variables for setting TLS settings.
The following configuration with the current provider ignores the environment variables whereas the backend respects them.
```
CONSUL_CLIENT_CERT="/path/to/cert"
CONSUL_CLIENT_KEY="/path/to/key"
CONSUL_CACERT="/path/to/cafile"
CONSUL_CAPATH="/path/to/capath"
terraform {
backend "consul" {
path = "terraform/state"
scheme = "https"
}
}
provider "consul" {
scheme = "https"
}
```
This change corrects this behavior and brings the provider in line with the behavior of the remote backend and Consul cli.
=> config.go properly sets TLS configuration

website/consul.erb, website/docs/d/agent_self.html.markdown, website/docs/guides/upgrading.html.markdown, website/docs/r/agent_service.html.markdown, website/docs/r/catalog_entry.html.markdown
We will soon be displaying documentation for this provider both on [terraform.io](https://www.terraform.io/docs/providers/index.html) and on [the Terraform Registry](https://registry.terraform.io/providers).
This PR moves guide documentation files to a dedicated subdirectory for guides. This enables the Registry to display these files distinctly from resources and data sources in the navigation tree. Links to these files in other documentation files are also updated to the new path.
For more information about how documentation is rendered on the Terraform Registry, please see this reference: [Terraform Registry - Provider Documentation](https://www.terraform.io/docs/registry/providers/docs.html).
=> website: Move guides to be ingressed by the Terraform Registry

consul/resource_consul_keys.go
The plan for for consul_keys resource always showed all unchanged keys
as being removed and added back making the diff hard to read:
```
~ resource "consul_keys" "product_vars" {
datacenter = "dc1"
id         = "consul"
~ var        = {} -> (known after apply)
- key {
- delete = true -> null
- flags  = 0 -> null
- path   = "products/xxx/env_vars/FOOBAR" -> null
- value  = "/password" -> null
}
- key {
- delete = true -> null
- flags  = 0 -> null
- path   = "products/xxx/env_vars/PASSWORD_PATH" -> null
- value  = "/password" -> null
}
- key {
- delete = true -> null
- flags  = 0 -> null
- path   = "products/xxxx/env_vars/INVITATION_PATH" -> null
- value  = "/invitation_old" -> null
}
+ key {
+ delete = true
+ flags  = 0
+ path   = "products/xxx/env_vars/FOOBAR"
+ value  = "/password"
}
+ …
```
=> Improve plans for consul_keys

.travis.yml
This is not possible for others providers since they require external
resources but we don't have this issue. While this will slow the CI a
bit it should help first time contributors and speed-up the review
process.
=> Run acceptance tests in Travis

consul/resource_consul_acl_policy.go, consul/resource_consul_acl_token.go, consul/resource_consul_acl_token_policy_attachment.go
Failing to read a policy or a token from the server does not necessarily mean
that the policy has been removed, the network can be down, the correct
datacenter may not be reachable etc. We must be conservative when
removing resources from the state and only create a new one if it's
actually needed.
=> Fix error checking in ACL resources

consul/resource_consul_key_prefix.go, consul/resource_consul_key_prefix_test.go
Resource ``consul_key_prefix``: Update of subkey blocks does not work properly.
In the first place, we find out that if one or more keys (created with ``subkey`` block) are manually removed in Consul, the provider does not detect it and doesn't recreate the missing key(s) (even if there's not key at all under this prefix).
When writing the fix for that, I find out that even adding new subkey blocks does not work properly.
It will add the new key but remove the existing ones (because of this [`continue`](https://github.com/terraform-providers/terraform-provider-consul/blob/aab0d40ed795ff184511514e17ff111397bef736/consul/resource_consul_key_prefix.go#L258) which continues the wrong for loop)
Then the provider will not detect that the mistakenly deleted keys are missing.
* I start a Consul …
=> consul_key_prefix: Fix update of subkey blocks.

website/docs/d/acl_token_secret_id.html.markdown
The documentation mentions `gpg_key` when the attribute is `pgp_key`
=> Fix typo in documentation: s/gpg_key/pgp_key/

website/docs/r/service.html.markdown
"Register an health-check" to "Register a health-check"
=> Fix typo in consul_service documentation

consul/data_source_consul_acl_auth_method_test.go, consul/data_source_consul_acl_policy_test.go, consul/data_source_consul_acl_role_test.go, consul/data_source_consul_acl_token_test.go, consul/data_source_consul_service_test.go, consul/data_source_consul_services_test.go, consul/resource_consul_acl_auth_method_test.go, consul/resource_consul_acl_binding_rule_test.go, consul/resource_consul_acl_policy_test.go, consul/resource_consul_acl_role_test.go, consul/resource_consul_acl_token_test.go, consul/resource_consul_keys_test.go, consul/resource_consul_namespace_test.go, consul/resource_consul_service_test.go
It changed change in Consul 1.8 from `"Namespaces is a Consul Enterprise feature"` to ``"Namespaces are a Consul Enterprise feature"`` so the regexp should match both versions.
=> Update regexp for Consul namespaces test in Community Edition

consul/resource_consul_config_entry_test.go, consul/resource_consul_intention.go, consul/resource_consul_intention_test.go, website/docs/r/intention.html.markdown
This patch should resolve #213, so that the `consul_intention` resource accepts datacenter as an argument, which is already reflected in existing documentation.
=> Fix datacenter handling in consul_intention

website/docs/r/node.html.markdown
Apparently this one was created from the consul_service doc and attributes were not corrected.
=> Replace "service" with "node" in attributes description

website/docs/d/acl_token_secret_id.html.markdown
It should be `consul_acl_token_secret_id` instead of `consul_acl_token`
```
Error: Reference to undeclared resource
on consul_token.tf line 22, in output "consul_acl_token_secret_id":
22:   value = data.consul_acl_token.read.encrypted_secret_id
A data resource "consul_acl_token" "read" has not been declared in the root
module.```
=> Fix typo in acl_token_secret_id datasource documentation

consul/config.go, consul/resource_provider.go, consul/resource_provider_test.go, website/docs/index.html.markdown
- Instead of paths only
```
Running tool: /usr/bin/go test -timeout 30s -run ^TestResourceProvider_ConfigureTLSPem$
2020/08/18 17:20:21 [INFO] Initializing Consul client
2020/08/18 17:20:21 [INFO] Consul Client configured with address: 'demo.consul.io:80', scheme: 'https', datacenter: 'nyc3', insecure_https: 'false'
PASS
ok  	github.com/terraform-providers/terraform-provider-consul/consul	0.029s
```
=> Allow specifying TLS Certificates via PEM strings

.travis.yml, GNUmakefile
CHANGELOG: no impact
Dockerhub is going to rate limit unauthenticated pulls on November 1st. IPs from CI machines (with the exception of github acitons) will be near their limit all the time. We're moving projects to use a public un-rate-limited Mirror of these images instead. Let me know if you have any q's, otherwise feel free to merge when you can!
=> Use docker mirror

consul/data_source_consul_acl_token_secret_id.go, consul/data_source_consul_acl_token_secret_id_test.go, website/docs/d/acl_token_secret_id.html.markdown
This PR enabled the tf provider to retrieve the token secret for ACL tokens scoped to a namespace.
=> Add namespaced token support to the consul_acl_token_secret_id data source

.gitattributes, consul/resource_consul_acl_token_policy_attachment.go, consul/resource_consul_acl_token_policy_attachment_test.go, consul/resource_consul_acl_token_role_attachment.go, consul/resource_consul_acl_token_role_attachment_test.go, consul/resource_provider.go, website/docs/r/acl_token_policy_attachment.html.markdown, website/docs/r/acl_token_role_attachment.html.markdown
This PR adds a new resource `consul_acl_token_role_attachment` that operates in the same fashion as the existing `consul_acl_token_policy_attachment`. This allows for the attachment of service identity policies supported through the `consul_acl_role` resource to existing tokens. 
The biggest use-case for me personally is to attach _policy_ to terminating gateway tokens that have been provisioned externally to the code provisioning the service which wants to make use of the terminating gateway. This can already be achieved using the `consul_acl_policy` and `consul_acl_token_policy_attachment` resources. However, the `consul_acl_role` offers a nice shortcut to creating the service identity policy. This pattern is also recommended in …
=> Add new resource `consul_acl_token_role_attachment`

consul/resource_consul_acl_auth_method.go, consul/resource_consul_acl_auth_method_test.go
Conditional logic was preventing resource updates as described in issue 240
Output from acceptance testing:
```
make testacc TEST=./consul TESTARGS='-run=TestAccConsulACLAuthMethod'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./consul -v -run=TestAccConsulACLAuthMethod -timeout 120m
=== RUN   TestAccConsulACLAuthMethod_basic
--- PASS: TestAccConsulACLAuthMethod_basic (0.54s)
=== RUN   TestAccConsulACLAuthMethod_namespaceCE
--- PASS: TestAccConsulACLAuthMethod_namespaceCE (0.06s)
=== RUN   TestAccConsulACLAuthMethod_namespaceEE
resource_consul_license_test.go:74: Test skipped on Consul Community Edition. Use a Consul Enterprise server to run this test.
--- SKIP: TestAccConsulACLAuthMethod_namespaceEE (0.02s)
PASS
ok …
```
=> Gh issue 240

consul/config.go
This define a custom RoundTripper to add the Content-Type header when
it is needed. This commit should be reverted once https://github.com/hashicorp/consul/pull/10204
is merged and released upstream.
I did not write a test for this change but tested locally and the
header is correctly present for PUT requests but not for GET or DELETE.
=> Use a temporary workaround to set the Content-Type header

website/docs/r/intention.html.markdown
Note that as of Consul 1.9 intentions should be managed using `consul_config_entry` instead of the `consul_intentions` resource.
=> docs: Add deprecation note for consul_intentions resource

consul/resource_consul_acl_auth_method.go, consul/resource_consul_acl_auth_method_test.go
Because CustomizeDiff is called early when not all values are known, we
cannot actually use it to check whether config or config_json is set.
This means that we have to delay checking this after the plan, when we
actually try to create or update it.
Closes https://github.com/hashicorp/terraform-provider-consul/issues/260
=> Handle interpolations properly in consul_acl_auth_method

GNUmakefile, README.md
Add instructions to the README on how to properly preview changes to documentation now that provider docs have been moved from Terraform.io to the Terraform registry.
This commit also removes the website target from the Makefile since it is no longer needed.
=> Add instructions for previewing doc changes

README.md, website/docs/d/acl_policy.html.markdown, website/docs/d/nodes.html.markdown, website/docs/d/service.html.markdown, website/docs/d/services.html.markdown, website/docs/guides/upgrading.html.markdown, website/docs/index.html.markdown, website/docs/r/acl_auth_method.markdown, website/docs/r/acl_token.html.markdown, website/docs/r/config_entry.markdown, website/docs/r/service.html.markdown
* Fix broken URL and markdownlint warnings in README
* Fix spelling errors in resource and data source docs
* Update Consul description on index page
* Fix erroneous reference to policy in auth method namespace param
I can squash some of these commits if you'd prefer to have a smaller changeset.
=> Minor documentation updates

README.md
It was written that "This provider targets the latest version of Consul" but some
users got confusing errors. Until I can spend some time to improve the status quo
and have a test setup accross multiple versions of Consul and this provider I
will report what combinations work there.
Related to https://github.com/hashicorp/terraform-provider-consul/issues/282
=> Add a compatibility table in the README

consul/data_source_consul_datacenters.go, consul/data_source_consul_datacenters_test.go, consul/resource_provider.go, website/docs/d/datacenters.html.markdown
This Pull request adds the `consul_datacenters` data source to the terraform-provider for consul.  This is my first Pull Request in Golang, so constructive criticism is welcome! I've added Docs and a test as well.
Thanks!
=> Feat: add consul datacenters

website/docs/index.html.markdown
removing reference to non existing Environment variable
=> Remove CONSUL_TOKEN from the documentation

.github/workflows/test.yaml, CHANGELOG.md, GNUmakefile, consul/data_source_consul_services_test.go, consul/resource_consul_config_entry.go, consul/resource_consul_config_entry_ce_test.go, consul/resource_consul_config_entry_ee_test.go, consul/resource_provider_test.go, website/docs/r/config_entry.markdown
Having the partition argument in `config_json` was causing an issue as
the provider was not reading the result back from the correct partition.
This is now fixed by having `partition` as an actual argument of
`consul_config_entry`.
Also, fix some flaky tests by improving the tests in startTestServer().
Also, simplify local testing by adding an install target in the Makefile.
=> Fix handling of partition in consul_config_entry

.github/workflows/release.yml, .goreleaser.yml, .release/release-metadata.hcl
This reflects the changes that acccompany the releases-api anticipated to be launched in early May. Included is:
* Version bump of the terraform provider release gh action
* Variables added for interfacing with releases-api
* hc-releases syntax modified for releases-api use
* metadata file added for ingesting with releases-api
=> [DO NOT MERGE] changes in anticipation of releases api transition

CHANGELOG.md, consul/data_source_consul_acl_token_secret_id.go, consul/data_source_consul_acl_token_secret_id_test.go, website/docs/d/acl_token_secret_id.html.markdown
This PR adds support for partitions to the `consul_acl_token_secret_id` resource.
Tokens can now be created with the `consul_acl_token` resource in non-default partitions and then have their secret ids retrieved with the data source.
=> Support partitioned tokens in ACL secret id data source

.github/workflows/test.yaml, consul/resource_consul_config_entry_ce_test.go, consul/resource_consul_config_entry_ee_test.go, docs/resources/config_entry.md
=> Add docs, examples and tests for jwt-provider config entry and jwt referencing intentions

consul/data_source_consul_acl_policy.go, consul/data_source_consul_acl_policy_test.go, consul/resource_consul_acl_auth_method_test.go, consul/resource_consul_acl_role_policy_attachment.go, consul/resource_consul_acl_role_policy_attachment_test.go
`resourceConsulACLRolePolicyAttachmentCreate()` and `resourceConsulACLRolePolicyAttachmentDelete()`
were not checking properly if the given role ID was not found in Consul.
Some functions in the Consul SDK return an error when the object is missing,
other return a `nil` object.
In the case of `RoleRead()` I was checking for the wrong thing. I checked the
rest of the ACL resources and as far as I know it, this was the only
resource impacted.
I also update the `consul_acl_policy` data source to use the new
`PolicyReadByName()` function.
Closes https://github.com/hashicorp/terraform-provider-consul/issues/378
=> Don't panic on missing role in consul_acl_role_policy_attachment

consul/resource_consul_peering_token.go, consul/resource_consul_peering_token_test.go, docs/resources/peering_token.md
Added ServerExternalAddresses field in the `consul_peering_token` resources in order to expose this field of the API.
Source: https://developer.hashicorp.com/consul/api-docs/v1.13.x/peering#serverexternaladdresses
=> Added ServerExternalAddresses for consul_peering_token

docs/resources/certificate_authority.md
I corrected a documentation error in the consul_certificate_authority resource. The example now correctly uses the jsonencode function instead of jsondecode.
```
#Using the built-in CA with specific TTL
resource "consul_certificate_authority" "connect" {
connect_provider = "consul"
config_json = jsonencode({
LeafCertTTL         = "24h"
RotationPeriod      = "2160h"
IntermediateCertTTL = "8760h"
})
}
```
=> fix documentation in Consul_certificate_authority examples

consul/resource_consul_config_entry_service_intentions.go
`jwt` is an optional parameter on the service intention config. When it was not set, the plugin would segfault due to a null pointer dereference on the ServiceIntentionsConfigEntry.JWT.
This adds a check for `si.JWT != nil` and skips building the `jwt` payload when it is not set.
Stack trace observed:
```
Stack trace from the terraform-provider-consul plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf0eb82]
goroutine 49 [running]:
github.com/hashicorp/terraform-provider-consul/consul.(*serviceIntentions).Write(0xc000b97598?, {0x14eb950?, 0xc000813100?}, 0xc00078c150?, 0x12?)
/tmp/guix-build-terraform-provider-consul-2.20.0.drv-0/source/source/consul/resource_consul_config_entry_service_intentions. …
```
=> consul_config_entry_service_intentions: Fix NPE when optional JWT unset

.github/workflows/test.yaml, consul/resource_consul_config_entry_ce_test.go, docs/resources/acl_binding_rule.md, examples/resources/consul_certificate_authority/resource.tf
Turns out the tests in this repo haven't been running since the primary branch was switched from `master` to `main`. Upon re-enabling them, there were a couple of failures that needed addressing around tf resource dependencies and generated docs.
=> Update test matrix to reflect latest Consul releases

docs/resources/service.md
The deregister_critical_service_after feature is not created by default via the API, however it is defaulted to 30s in the terraform provider. For users not wanting to use this feature we can pass a value that Consul will disable it.
It is noted in the consul codebase that setting this to a value less than 1 will disable however it will cause a warn level log entry here: https://github.com/hashicorp/consul/blob/cec66f07431191f8ddab5b74de15db36b34c9055/agent/agent.go#L3442
=> Documents disabling deregister_critical_service_after

.github/workflows/release.yml, consul/resource_consul_service.go
This version compensates for changes in GitHub's contract for custom runners
=> Consume latest release of ghaction-terraform-provider-release

.github/workflows/release.yml
Working through the failing release workflow ([example](https://github.com/hashicorp/terraform-provider-consul/actions/runs/10220656083/job/28281478131))
=> Consume latest version of actions/upload-artifact for compatibility

consul/resource_consul_admin_partition.go, consul/resource_consul_admin_partition_ent_test.go, docs/resources/admin_partition.md, templates/resources/admin_partition.md
Addresses #432  - Support DisableGossip for consul_admin_partition resource.
The DisableGossip field is already present in [type Partition](https://pkg.go.dev/github.com/hashicorp/consul/api#Partition) in the consul API. This PR adds the disable_gossip to the schema.
=> feat: add disable_gossip in admin partition to disable gossip pool
