consul/resource_consul_catalog_entry.go, consul/resource_consul_catalog_entry_test.go
=> Fix consul_catalog_entry creation notify on remove

GNUmakefile, README.md
This just makes it a bit easier for people to contribute and tries to point them in the right direction for testing.
=> Simplify getting started with readme/makefile updates

website/docs/index.html.markdown
See https://github.com/terraform-providers/terraform-provider-consul/issues/44#issuecomment-386100510.
=> website: add reference to consul token env vars

consul/resource_consul_service.go, consul/resource_consul_service_test.go
=> Add Consul service source metadata for UI integration

website/docs/r/node.html.markdown
=> Add documentation for datacenter attribute in consul_node resource

consul/data_source_consul_autopilot_health.go, consul/data_source_consul_autopilot_health_test.go, consul/resource_provider.go, website/consul.erb, website/docs/d/autopilot_health.html.markdown
See https://github.com/terraform-providers/terraform-provider-consul/issues/46#issue-319347046
=> Add consul_autopilot_health data source

website/docs/d/service.html.markdown
Brings documentation inline with the latest code: https://github.com/terraform-providers/terraform-provider-consul/blob/78a98d2e1f224f813fddc23954fa8b7beda9cac5/consul/data_source_consul_service.go#L16
=> Fix example in data.consul_service documentation

consul/resource_consul_autopilot_config.go, consul/resource_consul_autopilot_config_test.go, consul/resource_provider.go, website/consul.erb, website/docs/r/autopilot_config.html.markdown
See https://github.com/terraform-providers/terraform-provider-consul/issues/46#issue-319347046
=> Add the consul_autopilot_config resource

consul/resource_consul_keys.go
I think Consul will already default to the agent's datacenter for most (all?) operations. Should we just remove https://github.com/terraform-providers/terraform-provider-consul/blob/master/consul/resource_consul_keys.go#L347-L351 and return `""` instead?
Fix https://github.com/terraform-providers/terraform-provider-consul/issues/97
=> Default datacenter to "" if not readable in /agent/self

consul/resource_consul_service.go, consul/resource_consul_service_test.go
Solves #112 @remilapeyre I can't seem to get the tests to fail. I can't seem to figure out what they're actually doing. I'll add comments to lines to explain what I thought was true but obviously isn't.
=> Adding meta to consul_service

consul/data_source_consul_services_test.go, consul/query_options.go
This code is to fix defect #134.
I modified the  code for reading `query_options`
=> Fix issue query_options are not read #134

website/docs/r/service.html.markdown
Close https://github.com/terraform-providers/terraform-provider-consul/issues/131
=> Document meta attribute on consul_service resource

website/docs/index.html.markdown
The example to access a key in Consul should be a data source and not a resource
=> Use consul_keys data source in the index.html example

consul/resource_consul_service.go, consul/resource_consul_service_test.go
Closes https://github.com/terraform-providers/terraform-provider-consul/issues/146
=> Fix plan for consul_service when there is multiple service instances

.gitignore, .travis.yml, README.md, consul/resource_consul_license.go, consul/resource_consul_license_test.go, consul/resource_provider.go, website/consul.erb, website/docs/r/license.markdown
Closes https://github.com/terraform-providers/terraform-provider-consul/issues/172
=> Add consul_license resource

consul/resource_consul_acl_role.go, consul/resource_consul_acl_role_test.go, website/docs/r/acl_role.markdown
the ACL role should be importable just as a policy is.
=> Add import support to consul_acl_role

consul/data_source_consul_acl_token_secret_id.go
=> Fix error message in consul_acl_token datasource

consul/resource_consul_prepared_query.go, consul/resource_consul_prepared_query_test.go, website/docs/r/prepared_query.markdown
Closes https://github.com/terraform-providers/terraform-provider-consul/issues/192
=> Add ignore_check_ids, node_meta and service_meta to consul_prepared_query

consul/data_source_consul_acl_auth_method.go, consul/data_source_consul_acl_auth_method_test.go, consul/resource_consul_acl_auth_method.go, consul/resource_consul_acl_auth_method_test.go, consul/resource_consul_acl_role_test.go, website/docs/d/acl_auth_method.html.markdown, website/docs/r/acl_auth_method.markdown
Closes https://github.com/terraform-providers/terraform-provider-consul/issues/207
=> Add a config_json attribute to consul_acl_auth_method

website/docs/r/certificate_authority.html.markdown
Closes https://github.com/terraform-providers/terraform-provider-consul/issues/211
=> Fix resource name in consul_certificate_authority documentation

consul/resource_consul_license.go, consul/resource_provider.go, website/docs/r/license.markdown
Since this just removes an attribute it does not need a StateUpgrader.
Closes https://github.com/hashicorp/terraform-provider-consul/issues/223
=> Remove the flags attribute in consul_license

consul/resource_consul_intention.go, consul/resource_consul_intention_test.go, website/docs/r/intention.html.markdown
Closes https://github.com/hashicorp/terraform-provider-consul/issues/222
=> Add import support to consul_intention

consul/resource_provider.go
Closes https://github.com/terraform-providers/terraform-provider-consul/issues/215
=> Correctly handles environment variables for the protocol scheme

consul/resource_consul_acl_binding_rule.go, consul/resource_consul_acl_binding_rule_test.go
Closes https://github.com/terraform-providers/terraform-provider-consul/issues/217
=> Add support for the node binding rule

website/docs/r/key_prefix.html.markdown
I'm not entirely sure if this is the exact correct wording, but it looked like the existing description for the import needed a bit of re-working. Happy to iterate on this to make sure it makes sense to everyone and accurately reflects the import behavior! 🙂
=> Clarify the wording in the docs for consul_key_prefix import

consul/resource_consul_config_entry.go, consul/resource_consul_config_entry_test.go, consul/resource_consul_namespace_test.go, website/docs/r/config_entry.markdown
Closes https://github.com/hashicorp/terraform-provider-consul/issues/246
=> Add namespace support to consul_config_entry

consul/resource_consul_namespace.go, consul/resource_consul_namespace_test.go, website/docs/r/namespace.markdown
Closes https://github.com/hashicorp/terraform-provider-consul/issues/247
=> Make consul_namespace importable

consul/resource_consul_service.go, consul/resource_consul_service_test.go
Closes https://github.com/hashicorp/terraform-provider-consul/issues/237
=> Correctly detect outside changes in checks in consul_service

website/docs/r/config_entry.markdown
Closes https://github.com/hashicorp/terraform-provider-consul/issues/281
=> Add note regarding perpetual diffs in consul_config_entry documentation

website/docs/index.html.markdown
Reverts hashicorp/terraform-provider-consul#294
=> Revert "Remove CONSUL_TOKEN from the documentation"

docs/resources/service.md
Added partition to docs.
https://github.com/hashicorp/terraform-provider-consul/blob/edeffd2ae33747e0a65d5e4a9cb7398f16b4ecbb/consul/resource_consul_service.go#L209
=> Update resource consul_service documentation to include partition

consul/resource_consul_acl_role.go, consul/resource_consul_acl_role_test.go
Related to https://github.com/hashicorp/terraform-provider-consul/issues/344
=> Validate that the policies argument in consul_acl_role contains UUIDs

.github/workflows/test.yaml, README.md, templates/index.md.tmpl
Updated documentation for compatibility matrix of terraform consul provider with consul.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> update compatibility matrix between TF consul provider and consul in index.md template
